name: 'NuGet Deployment'

on:
  workflow_call:
  workflow_dispatch:
    
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x    
      - name: Pack
        run: dotnet pack --configuration release --output ${{ github.workspace}}/output/
      - name: Push
        run: dotnet nuget push ${{ github.workspace}}/output/*.nupkg --api-key ${{ secrets.NuGetToken }} --skip-duplicate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create GitHub Release
        run: "gh release create 'Release Test' --generate-notes"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}          
        